### ISSUE TITLE
invalid siblings selector in jquery.tabs.js

### ISSUE THREAD

**Issue by brunokindt** [Kunstmaan/cargobay#20]
```
$this.siblings(tabClassActive).removeClass(tabClassActive);
```
should be
```
$this.siblings('.' + tabClassActive).removeClass(tabClassActive);
```

in [jquery.tabs.js](https://github.com/Kunstmaan/cargobay/blob/master/src/tabs/js/jquery.tabs.js#L42) line 42

**Comment by IbeVanmeenen** [comment]
@brunokindt Thx, will be fixed in 1.0.0, stay tuned :)
